export const GET_ALL_ANNOUNCEMENT = "GET_ALL_ANNOUCEMENT";
export const GET_ALL_ANNOUNCEMENT_SUCCESS = "GET_ALL_ANNOUNCEMENT_SUCCESS";
export const GET_ALL_ANNOUNCEMENT_ERROR = "GET_ALL_ANNOUNCEMENT_ERROR";

export const SAVE_ANNOUNCEMENT = "SAVE_ANNOUNCEMENT";
export const SAVE_ANNOUNCEMENT_SUCCESS = "SAVE_ANNOUNCEMENT_SUCCESS";
export const SAVE_ANNOUNCEMENT_ERROR = "SAVE_ANNOUNCEMENT_ERROR";

export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS";
export const DELETE_ANNOUNCEMENT_ERROR = "DELETE_ANNOUNCEMENT_ERROR";
