export const GET_ALL_ANNOUNCEMENT = "GET_ALL_ANNOUCEMENT";
export const GET_ALL_ANNOUNCEMENT_SUCCESS = "GET_ALL_ANNOUNCEMENT_SUCCESS";
export const GET_ALL_ANNOUNCEMENT_ERROR = "GET_ALL_ANNOUNCEMENT_ERROR";
