export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISETER_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const GET_ALL_SOCIETIES = "GET_ALL_SOCIETIES";
export const GET_ALL_SOCIETIES_SUCCESS = "GET_ALL_SOCIETIES_SUCCESS";
export const GET_ALL_SOCIETIES_ERROR = "GET_ALL_SOCIETIES_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
