export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISETER_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const GET_ALL_SOCIETIES = "GET_ALL_SOCIETIES";
export const GET_ALL_SOCIETIES_SUCCESS = "GET_ALL_SOCIETIES_SUCCESS";
export const GET_ALL_SOCIETIES_ERROR = "GET_ALL_SOCIETIES_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_SOCITY_ID = "UPDATE_SOCITY_ID";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_ERROR = "UPDATE_USER_DETAILS_ERROR";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILURE = "FORGET_PASSWORD_FAILURE";

export const VERIFY_SOCIETY = "VERIFY_SOCIETY";
export const VERIFY_SOCIETY_SUCCESS = "VERIFY_SOCIETY_SUCCESS";
export const VERIFY_SOCIETY_FAILURE = "VERIFY_SOCIETY_FAILURE";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
