export const GET_ALL_COMPLAINT = "GET_ALL_COMPLAINT";
export const GET_ALL_COMPLAINT_SUCCESS = "GET_ALL_COMPLAINT_SUCCESS";
export const GET_ALL_COMPLAINT_ERROR = "GET_ALL_COMPLAINT_ERROR";

export const SAVE_COMPLAINT = "SAVE_COMPLAINT";
export const SAVE_COMPLAINT_SUCCESS = "SAVE_COMPLAINT_SUCCESS";
export const SAVE_COMPLAINT_ERROR = "SAVE_COMPLAINT_ERROR";

export const DELETE_COMPLAINT = "DELETE_COMPLAINT";
export const DELETE_COMPLAINT_SUCCESS = "DELETE_COMPLAINT_SUCCESS";
export const DELETE_COMPLAINT_ERROR = "DELETE_COMPLAINT_ERROR";
