export const FETCH_GALLERY = "FETCH_GALLERY";
export const FETCH_GALLERY_SUCCESS = "FETCH_GALLERY_SUCCESS";
export const FETCH_GALLERY_ERROR = "FETCH_GALLERY_ERROR";

export const CREATE_GALLERY = "CREATE_GALLERY";
export const CREATE_GALLERY_SUCCESS = "CREATE_GALLERY_SUCCESS";
export const CREATE_GALLERY_ERROR = "CREATE_GALLERY_ERROR";

export const DELETE_GALLERY = "DELETE_GALLERY";
export const DELETE_GALLERY_SUCCESS = "DELETE_GALLERY_SUCCESS";
export const DELETE_GALLERY_ERROR = "DELETE_GALLERY_ERROR";
